platform:ios, '7.0'

inhibit_all_warnings!

pod 'AFNetworking', '~> 2.2.3'
pod 'Parse', '~> 1.2.9'
pod 'pop', '~> 1.0.4'
pod 'STZPullToRefresh', '~> 0.0.1'
pod 'APParallaxHeader', '~> 0.1.3'
pod 'iRate', '~> 1.9.3'
pod 'IDMPhotoBrowser', '~> 1.3.5'
pod 'XHTwitterPaggingViewer'
pod 'UIActionSheet+Blocks', '~> 0.8.1'